# ============================================
# Generate Knowledge File from User Request
# ============================================
# Usage: .agent/commands/generate-knowledge.ps1 -Request "User request" -Files "file1.mqh,file2.mqh" -Priority "MEDIUM"

param(
    [Parameter(Mandatory=$true)]
    [string]$Request,
    
    [Parameter(Mandatory=$false)]
    [string]$Files = "",
    
    [Parameter(Mandatory=$false)]
    [ValidateSet("LOW", "MEDIUM", "HIGH", "CRITICAL")]
    [string]$Priority = "MEDIUM",
    
    [Parameter(Mandatory=$false)]
    [string]$RequirementID = ""
)

# ============================================
# Configuration
# ============================================
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$AgentDir = Split-Path -Parent $ScriptDir
$KnowledgeDir = Join-Path $AgentDir "knowledge"

# Create knowledge directory if not exists
if (-not (Test-Path $KnowledgeDir)) {
    New-Item -ItemType Directory -Path $KnowledgeDir -Force | Out-Null
}

# Generate Requirement ID if not provided
if ([string]::IsNullOrEmpty($RequirementID)) {
    $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $RequirementID = "REQ-$timestamp"
}

# Generate filename
$filename = "$RequirementID.md"
$filepath = Join-Path $KnowledgeDir $filename

# Current date/time
$currentDate = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

# ============================================
# Parse Files
# ============================================
$fileList = @()
if (-not [string]::IsNullOrEmpty($Files)) {
    $fileList = $Files -split "," | ForEach-Object { $_.Trim() }
}

# ============================================
# Generate Knowledge Content
# ============================================
$content = @"
# Requirement: $($Request.Substring(0, [Math]::Min(60, $Request.Length)))

## 📅 Metadata
- **Date**: $currentDate
- **Requirement ID**: $RequirementID
- **Status**: PENDING
- **Priority**: $Priority

## 🎯 User Request
$Request

## 📝 Detailed Requirements

### What to Change
"@

# Add file changes
if ($fileList.Count -gt 0) {
    foreach ($file in $fileList) {
        $content += @"

- [ ] File: ``$file``
  - Change: [To be determined]
  - Reason: [To be determined]
  - Impact: [To be determined]
"@
    }
} else {
    $content += @"

- [ ] Files to be determined based on analysis
"@
}

$content += @"

### Business Rules
- [Rules to be identified from context]

### Technical Constraints
- [Constraints to be identified from context]

## 🔍 Context

### Related Files
[To be populated by analyzing codebase]

### Current Implementation
[To be populated by reading current code]

### Expected Behavior
[To be determined based on requirements]

## ✅ Acceptance Criteria
- [ ] Requirements understood correctly
- [ ] Code changes implemented
- [ ] Tests passed (if applicable)
- [ ] Documentation updated
- [ ] No breaking changes

## 🔗 Related Knowledge
- `.cursorrules` - Code style and rules
- `docs/v2/` - Documentation structure

## 📝 Implementation Notes
[Will be updated during implementation]

## ✅ Verification Checklist
- [ ] Code changes implemented
- [ ] Tests passed
- [ ] Documentation updated
- [ ] No breaking changes

---

**Generated**: $currentDate  
**Auto-generated by**: generate-knowledge.ps1
"@

# ============================================
# Write Knowledge File
# ============================================
$content | Out-File -FilePath $filepath -Encoding UTF8

# ============================================
# Create/Update Current Requirement Link
# ============================================
$currentLink = Join-Path $KnowledgeDir "current-requirement.md"
$linkContent = @"
# Current Active Requirement

**Requirement ID**: $RequirementID  
**File**: ``$filename``  
**Status**: PENDING  
**Priority**: $Priority

## Quick Link
See full details: [$RequirementID]($filename)

## User Request
$Request

---

**Last Updated**: $currentDate
"@

$linkContent | Out-File -FilePath $currentLink -Encoding UTF8

# ============================================
# Output Result
# ============================================
Write-Host "`n✅ Knowledge file generated successfully!" -ForegroundColor Green
Write-Host "   File: $filepath" -ForegroundColor Cyan
Write-Host "   Requirement ID: $RequirementID" -ForegroundColor Cyan
Write-Host "   Current link: $currentLink" -ForegroundColor Cyan
Write-Host ""

return $filepath

